"""Register an externally-created service principal: write its credentials to .env.

The SP is created out-of-band (workspace UI / colleague / external tooling),
since minting an OAuth secret programmatically requires elevated privileges
the demo presenter doesn't typically have. This step just records the
credentials the presenter already has.

Sources for client_id / client_secret / sp_id, in priority order:
  1. explicit kwargs (CLI flags)
  2. ZB_CLIENT_ID / ZB_CLIENT_SECRET / ZB_SP_ID env vars
  3. existing .env file (lets `all` rerun without re-passing creds)
"""

from __future__ import annotations

import os

from setup.client import workspace_client
from setup.config import ENV_FILE, Config, load_dotenv


def _resolve(name: str, explicit: str | None, existing: dict[str, str]) -> str | None:
    return explicit or os.environ.get(name) or existing.get(name)


def run(
    cfg: Config,
    client_id: str | None = None,
    client_secret: str | None = None,
    sp_id: str | None = None,
) -> None:
    existing = load_dotenv()
    client_id = _resolve("ZB_CLIENT_ID", client_id, existing)
    client_secret = _resolve("ZB_CLIENT_SECRET", client_secret, existing)
    sp_id = _resolve("ZB_SP_ID", sp_id, existing)

    missing = [n for n, v in (("client_id", client_id), ("client_secret", client_secret)) if not v]
    if missing:
        raise RuntimeError(
            f"missing {', '.join(missing)}. Provide via:\n"
            "  --client-id / --client-secret flags, or\n"
            "  ZB_CLIENT_ID / ZB_CLIENT_SECRET env vars, or\n"
            f"  pre-populated {ENV_FILE} (see .env.example).\n"
            "Create the service principal + secret in the workspace UI under "
            "Settings > Identity and access > Service principals."
        )

    w = workspace_client(cfg.profile)
    host = w.config.host

    lines = [
        "# Generated by `python -m setup.cli register-sp` — DO NOT COMMIT",
        f"DATABRICKS_HOST={host}",
        f"ZB_CLIENT_ID={client_id}",
        f"ZB_CLIENT_SECRET={client_secret}",
        f"ZB_TABLE_FQN={cfg.fqn}",
    ]
    if sp_id:
        lines.append(f"ZB_SP_ID={sp_id}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    os.chmod(ENV_FILE, 0o600)

    print(f">> wrote {ENV_FILE}")
    if not sp_id:
        print(">> note: no ZB_SP_ID provided — `cleanup` will leave the SP intact")
    print(">> next:  python -m setup.cli grant")
